ACCEL_ASCII ""

(asciiHeader
  (asciiVersion 3 0)
  (timeStamp 2017 11 8 22 9 52)
  (program "Protel DXP" "Version 1.0.0.30000")
  (copyright "Copyright © Altium Limited 2015")
  (fileAuthor "")
  (headerString "")
  (fileUnits mil)
  (guidString "{00000000-0000-0000-0000-000000000000}")
)
(library "Library_1"
  (textStyleDef "(Default)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (textStyleAllowTType False)
    (textStyleDisplayTType False)
  )
  (textStyleDef "(PinStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 91.0)
      (strokeWidth 9.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PartStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(WireStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 60.0)
      (strokeWidth 9.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(PortStyle)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 60.0)
      (strokeWidth 9.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "(DefaultTTF)"
    (font
      (fontType Stroke)
      (fontFamily SanSerif)
      (fontFace "QUALITY")
      (fontHeight 100.0)
      (strokeWidth 10.0)
    )
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (textStyleDef "10pTIMESNEWROMAN"
    (font
      (fontType TrueType)
      (fontFamily Modern)
      (fontFace "Times New Roman")
      (fontHeight 139.0)
      (strokeWidth 0.19843 mm)
      (fontWeight 400)
      (fontItalic False)
      (fontCharSet 0)
      (fontOutPrecision 7)
      (fontClipPrecision 32)
      (fontQuality 1)
      (fontPitchAndFamily 6)
    )
    (textStyleAllowTType True)
    (textStyleDisplayTType True)
  )
  (symbolDef "STM32F030F4P6_1_N"
    (originalName "STM32F030F4P6_1_N")
    (pin (pinNum 1)  (pt 2700 5200) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 2800 5200) "1" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 2700 5200) "BOOT0" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 2700 5000) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 2800 5000) "4" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 2700 5000) "NRST" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 3)  (pt 1500 5800) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1400 5800) "6" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1500 5800) "PA0" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 4)  (pt 1500 5700) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1400 5700) "7" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1500 5700) "PA1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 5)  (pt 1500 5600) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1400 5600) "8" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1500 5600) "PA2" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 6)  (pt 1500 5500) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1400 5500) "9" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1500 5500) "PA3" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 7)  (pt 1500 5400) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1400 5400) "10" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1500 5400) "PA4" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 8)  (pt 1500 5300) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1400 5300) "11" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1500 5300) "PA5" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 9)  (pt 1500 5200) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1400 5200) "12" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1500 5200) "PA6" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 10)  (pt 1500 5100) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1400 5100) "13" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1500 5100) "PA7" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 11)  (pt 1500 5000) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1400 5000) "17" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1500 5000) "PA9" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 12)  (pt 1500 4900) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1400 4900) "18" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1500 4900) "PA10" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 13)  (pt 1500 4800) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1400 4800) "19" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1500 4800) "PA13(SWDIO)" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 14)  (pt 1500 4700) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1400 4700) "20" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1500 4700) "PA14(SWCLK)" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 15)  (pt 2700 5800) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 2800 5800) "14" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 2700 5800) "PB1" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 16)  (pt 2700 5600) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 2800 5600) "2" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 2700 5600) "PF0-OSC_IN(PF0)" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 17)  (pt 2700 5500) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 2800 5500) "3" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 2700 5500) "PF1-OSC_OUT(PF1)" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 18)  (pt 1500 4500) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1400 4500) "16" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1500 4500) "VDD" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 19)  (pt 1500 4400) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 1400 4400) "5" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 1500 4400) "VDDA" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 20)  (pt 2700 4500) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 2800 4500) "15" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 2700 4500) "VSS" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 1500 4300) (pt 1500 5900) (width 10) )
    (line (pt 1500 4300) (pt 2700 4300) (width 10) )
    (line (pt 1500 5900) (pt 2700 5900) (width 10) )
    (line (pt 2700 5900) (pt 2700 4300) (width 10) )
    (attr "RefDes" ""  (pt 1500 5900) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt 1500 4200) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "DatasheetVersion" "Rev. 1"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "PackageVersion" "Rev. 1, 11/2012"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "PackageReference" "TSSOP20"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "PackageDescription" "20-Pin Thin Shrink Small Outline Package, 6.5 x 4.4 mm Body, 0.65 mm Pitch"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Supplier 1" "Digi-Key"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Supplier Part Numb31" "497-14044-5-ND"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Supplier 2" "Newark"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Supplier Part Numb32" "06X3648"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Supplier 3" "Mouser"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Supplier Part Numb33" "511-STM32F030F4P6"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Core" "ARM Cortex-M0"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "FLASH Size (Prog) 29" "16"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "I/Os (High Current)" "15"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Internal RAM Size 29" "4"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Operating Frequenc29" "48"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Packing" "Tube"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Supply Voltage(Vcc29" "2.4"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Mounting Technology" "Surface Mount"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "PartNumber" "STM32F030F4P6"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "ComponentLink1Desc6E" "Manufacturer URL"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "ComponentLink1URL" "http://www.st.com/web/en/home.html"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "ComponentLink2Desc6E" "Datasheet"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "ComponentLink2URL" "http://www.st.com/st-web-ui/static/active/en/resource/technical/document/datasheet/DM00088500.pdf"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "ComponentLink3Desc6E" "Package Specification"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "ComponentLink3URL" "http://www.st.com/st-web-ui/static/active/en/resource/technical/document/datasheet/DM00065136.pdf"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (symbolDef "LED2_1_N"
    (originalName "LED2_1_N")
    (pin (pinNum 1)  (pt 700 6800) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt 600 6800) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 700 6800) "A" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 800 6800) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt 900 6800) "2" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 800 6800) "K" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (poly 
      (pt 700 6700)
      (pt 800 6800)
      (pt 700 6900)
    )
    (line (pt 840 6900) (pt 910 6970) (width 10) )
    (line (pt 800 6940) (pt 870 7010) (width 10) )
    (poly 
      (pt 910 6970)
      (pt 870 6950)
      (pt 890 6930)
    )
    (poly 
      (pt 870 7010)
      (pt 830 6990)
      (pt 850 6970)
    )
    (line (pt 800 6900) (pt 800 6700) (width 10) )
    (attr "RefDes" ""  (pt 690 7020) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt 690 6590) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Published" "8-Jun-2000"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "LatestRevisionDate" "17-Jul-2002"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "LatestRevisionNote" "Re-released for DXP Platform."  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "PackageVersion" "Feb-2002"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "PackageReference" "3.2X1.6X1.1"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Publisher" "Altium Limited"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "PackageDescription" "SM LED; 2 Flat Leads"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (symbolDef "CH340_1_N"
    (originalName "CH340_1_N")
    (pin (pinNum 1)  (pt 10200 6100) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 10300 6100) "9" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 10200 6100) "CTS#" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 10200 6200) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 10300 6200) "10" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 10200 6200) "DSR#" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 3)  (pt 10200 6300) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 10300 6300) "11" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 10200 6300) "RI#" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 4)  (pt 10200 6400) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 10300 6400) "12" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 10200 6400) "DCD#" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 5)  (pt 10200 6500) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 10300 6500) "13" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 10200 6500) "DTR#" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 6)  (pt 10200 6600) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 10300 6600) "14" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 10200 6600) "RTS#" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 7)  (pt 10200 6700) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 10300 6700) "15" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 10200 6700) "R232" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 8)  (pt 10200 6800) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 10300 6800) "16" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 10200 6800) "VCC" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 9)  (pt 9400 6100) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 9300 6100) "8" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 9400 6100) "XO" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 10)  (pt 9400 6200) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 9300 6200) "7" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 9400 6200) "XI" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 11)  (pt 9400 6300) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 9300 6300) "6" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 9400 6300) "UD-" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 12)  (pt 9400 6400) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 9300 6400) "5" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 9400 6400) "UD+" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 13)  (pt 9400 6500) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 9300 6500) "4" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 9400 6500) "V3" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 14)  (pt 9400 6600) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 9300 6600) "3" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 9400 6600) "RXD" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 15)  (pt 9400 6700) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 9300 6700) "2" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 9400 6700) "TXD" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 16)  (pt 9400 6800) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 9300 6800) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 9400 6800) "GND" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 10200 7000) (pt 9400 7000) (width 10) )
    (line (pt 10200 5900) (pt 10200 7000) (width 10) )
    (line (pt 9400 5900) (pt 10200 5900) (width 10) )
    (line (pt 9400 7000) (pt 9400 5900) (width 10) )
    (attr "RefDes" ""  (pt 9700 6900) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt 9700 5900) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "MF" "Eaton / Cutler Hammer"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Package" "None"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Availability" "Bad"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "MP" "CH340"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Price" "248.29 USD"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Value" "*"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (symbolDef "ZX62M-B-5P(01)_1_N"
    (originalName "ZX62M-B-5P(01)_1_N")
    (pin (pinNum 1)  (pt 6500 6600) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 6600 6600) "5" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 6500 6600) "GND" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 6500 6500) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 6600 6500) "4" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 6500 6500) "ID" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 3)  (pt 6500 6400) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 6600 6400) "3" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 6500 6400) "D+" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 4)  (pt 6500 6300) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 6600 6300) "2" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 6500 6300) "D-" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 5)  (pt 6500 6200) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 6600 6200) "1" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 6500 6200) "VCC" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 6500 6600) (pt 6450 6600) (width 10) )
    (line (pt 6500 6500) (pt 6450 6500) (width 10) )
    (line (pt 6500 6400) (pt 6450 6400) (width 10) )
    (line (pt 6500 6300) (pt 6450 6300) (width 10) )
    (line (pt 6500 6200) (pt 6450 6200) (width 10) )
    (line (pt 6500 6100) (pt 6600 6200) (width 10) )
    (line (pt 6200 6100) (pt 6500 6100) (width 10) )
    (line (pt 6200 6700) (pt 6200 6100) (width 10) )
    (line (pt 6500 6700) (pt 6200 6700) (width 10) )
    (line (pt 6600 6600) (pt 6500 6700) (width 10) )
    (line (pt 6600 6200) (pt 6600 6600) (width 10) )
    (attr "RefDes" ""  (pt 6300 6800) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt 6000 6000) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Availability" "Unavailable"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "MP" "ZX62M-B-5P(01)"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Price" "None"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Package" "None"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "MF" "Hirose"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Value" "*"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (symbolDef "LM2937IMP-12_1_N"
    (originalName "LM2937IMP-12_1_N")
    (pin (pinNum 1)  (pt 8100 5400) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 8200 5400) "3" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 8100 5400) "VOUT" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 6900 5300) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 6800 5300) "4" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 6900 5300) "GND_(TAB)" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 3)  (pt 6900 5400) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 6800 5400) "2" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 6900 5400) "GND" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 4)  (pt 6900 5600) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName True) )
      (pinDes    (text  (pt 6800 5600) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 6900 5600) "VIN" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 8100 5800) (pt 6900 5800) (width 10) )
    (line (pt 8100 5100) (pt 8100 5800) (width 10) )
    (line (pt 6900 5100) (pt 8100 5100) (width 10) )
    (line (pt 6900 5800) (pt 6900 5100) (width 10) )
    (attr "RefDes" ""  (pt 7313.813 5853.254) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt 7214.683 4994.327) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Availability" "Unavailable"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "MP" "LM2937IMP-12"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Price" "None"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Package" "SOT-223 Fairchild Semiconductor"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "MF" "Fairchild Semiconductor"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Value" "*"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (symbolDef "XTAL_1_N"
    (originalName "XTAL_1_N")
    (pin (pinNum 1)  (pt 9100 5200) (rotation 180.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt 9000 5200) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 9100 5200) "OSC1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 9200 5200) (rotation 0.0) (isFlipped False) (pinLength 200)
      (pinDisplay (dispPinDes True) (dispPinName False) )
      (pinDes    (text  (pt 9300 5200) "2" (textStyleRef "(PinStyle)") (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 9200 5200) "OSC2" (textStyleRef "(PinStyle)") (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 9200 5240) (pt 9200 5160) (width 10) )
    (line (pt 9120 5270) (pt 9180 5270) (width 10) )
    (line (pt 9100 5240) (pt 9100 5160) (width 10) )
    (line (pt 9180 5270) (pt 9180 5130) (width 10) )
    (line (pt 9180 5130) (pt 9120 5130) (width 10) )
    (line (pt 9120 5130) (pt 9120 5270) (width 10) )
    (attr "RefDes" ""  (pt 9090 5280) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt 9090 5020) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Published" "8-Jun-2000"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "LatestRevisionDate" "17-Jul-2002"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "LatestRevisionNote" "Re-released for DXP Platform."  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "PackageReference" "R38"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Publisher" "Altium Limited"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "PackageDescription" "Crystal, Thru-Hole; 2 Leads; Body 3.1 x 8.2 mm (Dia.xH)"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (symbolDef "Cap_Semi_1_N"
    (originalName "Cap_Semi_1_N")
    (pin (pinNum 1)  (pt 9600 4600) (rotation 270.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt 9600 4550) "1" (textStyleRef "(PinStyle)") (rotation 270.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 9600 4600) "1" (textStyleRef "(PinStyle)") (rotation 270.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (pin (pinNum 2)  (pt 9600 4700) (rotation 90.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt 9600 4750) "2" (textStyleRef "(PinStyle)") (rotation 90.0) (justify LowerCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 9600 4700) "2" (textStyleRef "(PinStyle)") (rotation 90.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 9520 4670) (pt 9680 4670) (width 10) )
    (line (pt 9680 4630) (pt 9520 4630) (width 10) )
    (line (pt 9600 4600) (pt 9600 4630) (width 10) )
    (line (pt 9600 4700) (pt 9600 4670) (width 10) )
    (attr "RefDes" ""  (pt 9690 4610) (isVisible True) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Type" ""  (pt 9690 4510) (isVisible False) (justify LowerLeft) (textStyleRef "(PartStyle)") )
    (attr "Published" "8-Jun-2000"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "LatestRevisionDate" "29-May-2009"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "LatestRevisionNote" "IPC-7351 Footprint Added."  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "PackageReference" "C1206"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Publisher" "Altium Limited"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "PackageDescription" "Chip Capacitor"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Value" "22pF"  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (symbolDef "VCC_1_N"
    (originalName "VCC_1_N")
    (pin (pinNum 1)  (pt 100 0) (rotation 180.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt 50 0) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 100 0) "PWR" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 100 -100) (pt 100 100) (width 15) )
    (attr "Type" ""  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "RefDes" ""  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Value" ""  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (symbolDef "GND_1_N"
    (originalName "GND_1_N")
    (pin (pinNum 1)  (pt 100 0) (rotation 180.0) (isFlipped False) (pinLength 100)
      (pinDisplay (dispPinDes False) (dispPinName False) )
      (pinDes    (text  (pt 50 0) "1" (textStyleRef "(PinStyle)") (rotation 180.0) (justify UpperCenter) (extent 0.0 0.0) )
      )
      (pinName    (text  (pt 100 0) "GND" (textStyleRef "(PinStyle)") (rotation 180.0) (justify Right) (extent 0.0 0.0) )
      )
    )
    (line (pt 110 100) (pt 110 -100) (width 15) )
    (line (pt 140 70) (pt 140 -70) (width 15) )
    (line (pt 170 40) (pt 170 -40) (width 15) )
    (line (pt 200 10) (pt 200 -10) (width 15) )
    (attr "Type" ""  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "RefDes" ""  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
    (attr "Value" ""  (pt 0.0 0.0) (isVisible False) (textStyleRef "(Default)") )
  )
  (compDef "VCC"
    (originalName "VCC")
    (compHeader
      (sourceLibrary "")
      (compType Power)
      (numPins 1)
      (numParts 1)
      (refDesPrefix "P")
    )
    (compPin "1" (pinName "VCC") (partNum 1) (symPinNum 1) (gateEq 1) (pinEq 0) (pinType Power))
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "VCC_1_N") )
  )
  (compDef "GND"
    (originalName "GND")
    (compHeader
      (sourceLibrary "")
      (compType Power)
      (numPins 1)
      (numParts 1)
      (refDesPrefix "P")
    )
    (compPin "1" (pinName "GND") (partNum 1) (symPinNum 1) (gateEq 1) (pinEq 0) (pinType Power))
    (attachedSymbol (partNum 1) (altType Normal) (symbolName "GND_1_N") )
  )
)

(netlist "Netlist_1"
  (compInst "C?"
    (compRef "CAP_SEMI")
    (originalName "Cap_Semi")
    (compValue "22pF")
    (patternName "C1206")
    (attr "LatestRevisionDate" "29-May-2009" (pt 10 220) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "LatestRevisionNote" "IPC-7351 Footprint Added." (pt 10 220) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "PackageDescription" "Chip Capacitor" (pt 10 220) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "PackageReference" "C1206" (pt 10 220) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Published" "8-Jun-2000" (pt 10 220) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Publisher" "Altium Limited" (pt 10 220) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "C?"
    (compRef "CAP_SEMI")
    (originalName "Cap_Semi")
    (compValue "22pF")
    (patternName "C1206")
    (attr "LatestRevisionDate" "29-May-2009" (pt 10 220) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "LatestRevisionNote" "IPC-7351 Footprint Added." (pt 10 220) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "PackageDescription" "Chip Capacitor" (pt 10 220) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "PackageReference" "C1206" (pt 10 220) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Published" "8-Jun-2000" (pt 10 220) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
    (attr "Publisher" "Altium Limited" (pt 10 220) (justify LowerLeft) (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "D?"
    (compRef "LED2")
    (originalName "LED2")
    (patternName "3.2X1.6X1.1")
    (attr "LatestRevisionDate" "17-Jul-2002" (textStyleRef "(Default)") (constraintUnits string))
    (attr "LatestRevisionNote" "Re-released for DXP Platform." (textStyleRef "(Default)") (constraintUnits string))
    (attr "PackageDescription" "SM LED; 2 Flat Leads" (textStyleRef "(Default)") (constraintUnits string))
    (attr "PackageReference" "3.2X1.6X1.1" (textStyleRef "(Default)") (constraintUnits string))
    (attr "PackageVersion" "Feb-2002" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Published" "8-Jun-2000" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Publisher" "Altium Limited" (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "P?"
    (compRef "ZX62M-B-5P(01)")
    (originalName "ZX62M-B-5P(01)")
    (patternName "HRS_ZX62M-B-5P(01)")
    (attr "Availability" "Unavailable" (textStyleRef "(Default)") (constraintUnits string))
    (attr "MF" "Hirose" (textStyleRef "(Default)") (constraintUnits string))
    (attr "MP" "ZX62M-B-5P(01)" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Package" "None" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Price" "None" (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "U?"
    (compRef "LM2937IMP-12")
    (originalName "LM2937IMP-12")
    (patternName "SOT230P700X180-4N")
    (attr "Availability" "Unavailable" (textStyleRef "(Default)") (constraintUnits string))
    (attr "MF" "Fairchild Semiconductor" (textStyleRef "(Default)") (constraintUnits string))
    (attr "MP" "LM2937IMP-12" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Package" "SOT-223 Fairchild Semiconductor" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Price" "None" (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "U?"
    (compRef "CH340")
    (originalName "CH340")
    (patternName "SO16")
    (attr "Availability" "Bad" (textStyleRef "(Default)") (constraintUnits string))
    (attr "MF" "Eaton / Cutler Hammer" (textStyleRef "(Default)") (constraintUnits string))
    (attr "MP" "CH340" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Package" "None" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Price" "248.29 USD" (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "U?"
    (compRef "STM32F030F4P6")
    (originalName "STM32F030F4P6")
    (patternName "STM-TSSOP20_N")
    (attr "ComponentLink1Desc6E" "Manufacturer URL" (textStyleRef "(Default)") (constraintUnits string))
    (attr "ComponentLink1URL" "http://www.st.com/web/en/home.html" (textStyleRef "(Default)") (constraintUnits string))
    (attr "ComponentLink2Desc6E" "Datasheet" (textStyleRef "(Default)") (constraintUnits string))
    (attr "ComponentLink2URL" "http://www.st.com/st-web-ui/static/active/en/resource/technical/document/datasheet/DM00088500.pdf" (textStyleRef "(Default)") (constraintUnits string))
    (attr "ComponentLink3Desc6E" "Package Specification" (textStyleRef "(Default)") (constraintUnits string))
    (attr "ComponentLink3URL" "http://www.st.com/st-web-ui/static/active/en/resource/technical/document/datasheet/DM00065136.pdf" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Core" "ARM Cortex-M0" (textStyleRef "(Default)") (constraintUnits string))
    (attr "DatasheetVersion" "Rev. 1" (textStyleRef "(Default)") (constraintUnits string))
    (attr "FLASH Size (Prog) 29" "16" (textStyleRef "(Default)") (constraintUnits string))
    (attr "I/Os (High Current)" "15" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Internal RAM Size 29" "4" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Mounting Technology" "Surface Mount" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Operating Frequenc29" "48" (textStyleRef "(Default)") (constraintUnits string))
    (attr "PackageDescription" "20-Pin Thin Shrink Small Outline Package, 6.5 x 4.4 mm Body, 0.65 mm Pitch" (textStyleRef "(Default)") (constraintUnits string))
    (attr "PackageReference" "TSSOP20" (textStyleRef "(Default)") (constraintUnits string))
    (attr "PackageVersion" "Rev. 1, 11/2012" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Packing" "Tube" (textStyleRef "(Default)") (constraintUnits string))
    (attr "PartNumber" "STM32F030F4P6" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Supplier 1" "Digi-Key" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Supplier 2" "Newark" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Supplier 3" "Mouser" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Supplier Part Numb31" "497-14044-5-ND" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Supplier Part Numb32" "06X3648" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Supplier Part Numb33" "511-STM32F030F4P6" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Supply Voltage(Vcc29" "2.4" (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "Y?"
    (compRef "XTAL")
    (originalName "XTAL")
    (patternName "R38")
    (attr "LatestRevisionDate" "17-Jul-2002" (textStyleRef "(Default)") (constraintUnits string))
    (attr "LatestRevisionNote" "Re-released for DXP Platform." (textStyleRef "(Default)") (constraintUnits string))
    (attr "PackageDescription" "Crystal, Thru-Hole; 2 Leads; Body 3.1 x 8.2 mm (Dia.xH)" (textStyleRef "(Default)") (constraintUnits string))
    (attr "PackageReference" "R38" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Published" "8-Jun-2000" (textStyleRef "(Default)") (constraintUnits string))
    (attr "Publisher" "Altium Limited" (textStyleRef "(Default)") (constraintUnits string))
  )
  (compInst "PVCC1"
    (compRef "VCC")
    (originalName "VCC")
  )
  (compInst "GND1"
    (compRef "GND")
    (originalName "GND")
  )
  (compInst "PVCC2"
    (compRef "VCC")
    (originalName "VCC")
  )
  (compInst "GND2"
    (compRef "GND")
    (originalName "GND")
  )
  (compInst "GND3"
    (compRef "GND")
    (originalName "GND")
  )
  (compInst "GND4"
    (compRef "GND")
    (originalName "GND")
  )
  (compInst "PVCC3"
    (compRef "VCC")
    (originalName "VCC")
  )
  (compInst "PVCC4"
    (compRef "VCC")
    (originalName "VCC")
  )
  (compInst "PVCC5"
    (compRef "VCC")
    (originalName "VCC")
  )
  (compInst "GND5"
    (compRef "GND")
    (originalName "GND")
  )
  (compInst "GND6"
    (compRef "GND")
    (originalName "GND")
  )
  (net "GND"
    (node "C?" "1")
    (node "C?" "1")
    (node "P?" "5")
    (node "U?" "1")
    (node "U?" "2")
    (node "U?" "4")
    (node "U?" "15")
    (node "GND1" "1")
    (node "GND2" "1")
    (node "GND3" "1")
    (node "GND4" "1")
    (node "GND5" "1")
    (node "GND6" "1")
  )
  (net "NetC?_2"
    (node "C?" "2")
    (node "U?" "8")
    (node "Y?" "2")
    (node "C?" "2")
    (node "U?" "7")
    (node "Y?" "1")
  )
  (net "NetD?_2"
    (node "D?" "2")
    (node "U?" "6")
  )
  (net "NetP?_1"
    (node "P?" "1")
    (node "U?" "1")
  )
  (net "NetP?_2"
    (node "P?" "2")
    (node "U?" "6")
  )
  (net "NetP?_3"
    (node "P?" "3")
    (node "U?" "5")
  )
  (net "NetU?_2"
    (node "U?" "2")
    (node "U?" "3")
    (node "U?" "2")
    (node "U?" "3")
  )
  (net "NetU?_4"
    (node "U?" "4")
  )
  (net "VCC"
    (node "D?" "1")
    (node "U?" "3")
    (node "U?" "4")
    (node "U?" "16")
    (node "U?" "16")
    (node "PVCC1" "1")
    (node "PVCC2" "1")
    (node "PVCC3" "1")
    (node "PVCC4" "1")
    (node "PVCC5" "1")
  )
)

(schematicDesign "SchDesign_1"
  (schDesignHeader
    (workspaceSize 11500 7600)
    (gridDfns
      (grid "100mil")
    )
    (designInfo
      (fieldSet "(Default)"
        (fieldDef "Time" "")
        (fieldDef "Date" "")
        (fieldDef "Approved By" "")
        (fieldDef "Checked By" "")
        (fieldDef "Author" "")
        (fieldDef "Company Name" "")
        (fieldDef "Drawn By" "")
        (fieldDef "Engineer" "")
        (fieldDef "Organization" "")
        (fieldDef "Address1" "")
        (fieldDef "Address2" "")
        (fieldDef "Address3" "")
        (fieldDef "Address4" "")
        (fieldDef "Title" "")
        (fieldDef "Drawing Number" "")
        (fieldDef "Revision" "")
        (fieldDef "Rule" "")
        (fieldDef "ImagePath" "")
        (fieldDef "ProjectName" "")
        (fieldDef "Application_BuildNumber" "")
      )
    )
    (refPointSize 100)
    (infoPointSize 100)
    (junctionSize 20)
    (refPointSizePrint 100)
    (infoPointSizePrint 100)
    (junctionSizePrint 20)
  )

  (sheet "Sheet1" (sheetNum 1)
    (titleSheet ""
      1.0000
      (isVisible True)
      (offset 0.0 0.0)
      (border
        (isVisible True)
        (height 7600)
        (width 11500)
        (offset 0 0)
      )
      (zones
        (isVisible True)
        (textStyleRef "(Default)")
        (horizontalZones 4
          (numDirection ascending)
          (numType Alphabetic)
        )
        (verticalZones 4
          (numDirection ascending)
          (numType Numeric)
        )
      )
    )
    (fieldSetRef "(Default)")
    (wire (line (pt 10500 6800) (pt 10400 6800) (width 10) (netNameRef "VCC") )
    )
    (wire (line (pt 9000 6500) (pt 9200 6500) (width 10) (netNameRef "VCC") )
    )
    (wire (line (pt 8300 5600) (pt 8300 5400) (width 10) (netNameRef "VCC") )
    )
    (wire (line (pt 800 4500) (pt 1300 4500) (width 10) (netNameRef "VCC") )
    )
    (wire (line (pt 9200 6100) (pt 9100 6100) (width 10) (netNameRef "NetC?_2") )
    )
    (wire (line (pt 9100 6100) (pt 9100 5500) (width 10) (netNameRef "NetC?_2") )
    )
    (wire (line (pt 9100 5500) (pt 9600 5500) (width 10) (netNameRef "NetC?_2") )
    )
    (wire (line (pt 9600 5500) (pt 9600 5200) (width 10) (netNameRef "NetC?_2") )
    )
    (wire (line (pt 9600 5200) (pt 9600 4800) (width 10) (netNameRef "NetC?_2") )
    )
    (wire (line (pt 9600 5200) (pt 9400 5200) (width 10) (netNameRef "NetC?_2") )
    )
    (wire (line (pt 9200 6200) (pt 8800 6200) (width 10) (netNameRef "NetC?_2") )
    )
    (wire (line (pt 8800 6200) (pt 8800 5200) (width 10) (netNameRef "NetC?_2") )
    )
    (wire (line (pt 8800 5200) (pt 8800 4900) (width 10) (netNameRef "NetC?_2") )
    )
    (wire (line (pt 8800 5200) (pt 8900 5200) (width 10) (netNameRef "NetC?_2") )
    )
    (wire (line (pt 6700 6200) (pt 6700 5600) (width 10) (netNameRef "NetP?_1") )
    )
    (wire (line (pt 6700 6300) (pt 9200 6300) (width 10) (netNameRef "NetP?_2") )
    )
    (wire (line (pt 6700 6400) (pt 9200 6400) (width 10) (netNameRef "NetP?_3") )
    )
    (wire (line (pt 8800 6800) (pt 9200 6800) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 6700 5400) (pt 6700 5300) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 6200 5400) (pt 6700 5400) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 6700 6600) (pt 6800 6600) (width 10) (netNameRef "GND") )
    )
    (wire (line (pt 2900 4500) (pt 3400 4500) (width 10) (netNameRef "GND") )
    )
    (port (pt 8800 6700) (portType BothAngle_Dbl_Horz) (portPinLength PortPinLong) (netNameRef "NetU?_2") )
    (port (pt 2900 5500) (portType BothAngle_Dbl_Horz) (portPinLength PortPinLong) (netNameRef "NetU?_2") )
    (port (pt 8800 6600) (portType BothAngle_Dbl_Horz) (portPinLength PortPinLong) (netNameRef "NetU?_2") )
    (port (pt 2900 5600) (portType BothAngle_Dbl_Horz) (portPinLength PortPinLong) (netNameRef "NetU?_2") )
    (port (pt 2900 5000) (portType BothAngle_Dbl_Horz) (portPinLength PortPinLong) (netNameRef "NetU?_4") )
    (port (pt 1000 5800) (portType BothAngle_Dbl_Horz) (portPinLength PortPinLong) (netNameRef "NetD?_2") )
    (port (pt 1000 6800) (portType BothAngle_Dbl_Horz) (portPinLength PortPinLong) (netNameRef "NetD?_2") )
    (symbol (symbolRef "STM32F030F4P6_1_N") (refDesRef "U?") (partNum 1) (pt 1500 5900)
      (attr "RefDes" "U?" (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "DatasheetVersion" "Rev. 1" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "PackageVersion" "Rev. 1, 11/2012" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "PackageReference" "TSSOP20" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "PackageDescription" "20-Pin Thin Shrink Small Outline Package, 6.5 x 4.4 mm Body, 0.65 mm Pitch" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Supplier 1" "Digi-Key" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Supplier Part Numb31" "497-14044-5-ND" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Supplier 2" "Newark" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Supplier Part Numb32" "06X3648" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Supplier 3" "Mouser" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Supplier Part Numb33" "511-STM32F030F4P6" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Core" "ARM Cortex-M0" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "FLASH Size (Prog) 29" "16" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "I/Os (High Current)" "15" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Internal RAM Size 29" "4" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Operating Frequenc29" "48" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Packing" "Tube" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Supply Voltage(Vcc29" "2.4" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Mounting Technology" "Surface Mount" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "PartNumber" "STM32F030F4P6" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink1Desc6E" "Manufacturer URL" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink1URL" "http://www.st.com/web/en/home.html" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink2Desc6E" "Datasheet" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink2URL" "http://www.st.com/st-web-ui/static/active/en/resource/technical/document/datasheet/DM00088500.pdf" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink3Desc6E" "Package Specification" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "ComponentLink3URL" "http://www.st.com/st-web-ui/static/active/en/resource/technical/document/datasheet/DM00065136.pdf" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "STM32F030F4P6" (pt 0 -1700) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "VCC_1_N") (refDesRef "PVCC1") (partNum 1) (pt 800 4500) (rotation 180.0) )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND1") (partNum 1) (pt 3400 4500) (rotation 270.0) )
    (symbol (symbolRef "LED2_1_N") (refDesRef "D?") (partNum 1) (pt 700 6900)
      (attr "RefDes" "D?" (pt -10 120) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Published" "8-Jun-2000" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "LatestRevisionDate" "17-Jul-2002" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "LatestRevisionNote" "Re-released for DXP Platform." (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "PackageVersion" "Feb-2002" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "PackageReference" "3.2X1.6X1.1" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Publisher" "Altium Limited" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "PackageDescription" "SM LED; 2 Flat Leads" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "LED2" (pt -10 -310) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "VCC_1_N") (refDesRef "PVCC2") (partNum 1) (pt 500 6800) (rotation 90.0) )
    (symbol (symbolRef "CH340_1_N") (refDesRef "U?") (partNum 1) (pt 9900 6300)
      (attr "RefDes" "U?" (pt -200 600) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MF" "Eaton / Cutler Hammer" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Package" "None" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Availability" "Bad" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MP" "CH340" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Price" "248.29 USD" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "CH340" (pt -200 -400) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "ZX62M-B-5P(01)_1_N") (refDesRef "P?") (partNum 1) (pt 6400 6400) (rotation 180.0)
      (attr "RefDes" "P?" (pt -100 400) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Availability" "Unavailable" (rotation 180.0) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MP" "ZX62M-B-5P(01)" (rotation 180.0) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Price" "None" (rotation 180.0) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Package" "None" (rotation 180.0) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MF" "Hirose" (rotation 180.0) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "ZX62M-B-5P(01)" (pt -400 -400) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "LM2937IMP-12_1_N") (refDesRef "U?") (partNum 1) (pt 7500 5600)
      (attr "RefDes" "U?" (pt -186.187 253.254) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Availability" "Unavailable" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MP" "LM2937IMP-12" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Price" "None" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Package" "SOT-223 Fairchild Semiconductor" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "MF" "Fairchild Semiconductor" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "LM2937IMP-3.3" (pt -285.317 -605.673) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND2") (partNum 1) (pt 6800 6600) (rotation 0.0) )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND3") (partNum 1) (pt 6200 5400) (rotation 180.0) )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND4") (partNum 1) (pt 8800 6800) (rotation 180.0) )
    (symbol (symbolRef "VCC_1_N") (refDesRef "PVCC3") (partNum 1) (pt 8300 5600) (rotation 90.0) )
    (symbol (symbolRef "VCC_1_N") (refDesRef "PVCC4") (partNum 1) (pt 9000 6500) (rotation 180.0) )
    (symbol (symbolRef "VCC_1_N") (refDesRef "PVCC5") (partNum 1) (pt 10500 6800) (rotation 0.0) )
    (symbol (symbolRef "XTAL_1_N") (refDesRef "Y?") (partNum 1) (pt 9100 5300)
      (attr "RefDes" "Y?" (pt -10 -20) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Published" "8-Jun-2000" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "LatestRevisionDate" "17-Jul-2002" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "LatestRevisionNote" "Re-released for DXP Platform." (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "PackageReference" "R38" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Publisher" "Altium Limited" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "PackageDescription" "Crystal, Thru-Hole; 2 Leads; Body 3.1 x 8.2 mm (Dia.xH)" (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "12MHZ" (pt -10 -280) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "Cap_Semi_1_N") (refDesRef "C?") (partNum 1) (pt 9500 4600) (rotation 90.0)
      (attr "RefDes" "C?" (pt 190 10) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Published" "8-Jun-2000" (pt 10 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "LatestRevisionDate" "29-May-2009" (pt 10 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "LatestRevisionNote" "IPC-7351 Footprint Added." (pt 10 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "PackageReference" "C1206" (pt 10 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Publisher" "Altium Limited" (pt 10 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "PackageDescription" "Chip Capacitor" (pt 10 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Value" "22pF" (pt 190 -190) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "Cap Semi" (pt 190 -90) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "Cap_Semi_1_N") (refDesRef "C?") (partNum 1) (pt 8700 4700) (rotation 90.0)
      (attr "RefDes" "C?" (pt 190 10) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Published" "8-Jun-2000" (pt 10 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "LatestRevisionDate" "29-May-2009" (pt 10 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "LatestRevisionNote" "IPC-7351 Footprint Added." (pt 10 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "PackageReference" "C1206" (pt 10 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Publisher" "Altium Limited" (pt 10 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "PackageDescription" "Chip Capacitor" (pt 10 220) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Value" "22pF" (pt 190 -190) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
      (attr "Comment" "Cap Semi" (pt 190 -90) (isVisible true) (textStyleRef "(PartStyle)") (constraintUnits string) )
    )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND5") (partNum 1) (pt 8800 4600) (rotation 270.0) )
    (symbol (symbolRef "GND_1_N") (refDesRef "GND6") (partNum 1) (pt 9600 4500) (rotation 270.0) )
  )
  (schematicPrintSettings
    (sheetList
      (sheetRef 2)
    )
  )
  (programState
    (gridState
      (currentAbsGrid "100mil")
      (currentRelGrid "100mil")
      (isAbsoluteGrid True)
      (isDottedGrid True)
      (isVisibleGrid True)
      (isPromptForRel False)
    )
    (ecoState (ecoRecording False))
    (currentTextStyle "(Default)")
  )
)
